version: "3.9"
services:
  web:
    build: .      
    ports:
      - "9000:8765"
    volumes:
            - webapp_volume:/cms
            - "./app_config/config:/cms/config"
    links:
      - "db:database"
    depends_on:
      - "db" 
    networks:
      - backend
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cake
    ports:
      - '5432:5432'
    volumes:
            - database_volume:/var/lib/postgresql/data
            - "./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf"
    networks:
            backend:
                    aliases:
                           - psql 

volumes:
  webapp_volume:
  database_volume:
networks:
   backend:
