version: "3.9"
services:
  web:
    build: .      
    ports:
      - "9000:8765"
    volumes:
            - webapp_volume:/opt/webdata

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
            - database_volume:/opt/dbdata

volumes:
  webapp_volume:
  database_volume:

